apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-install
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mnagel/install-test:5e2ef3e2c6e26d7edae94b6082a167ca7b919254@sha256:52df36a7f5c2f5252b93d3165c3975861e3ab03d4bed39047b0f9a6ad29ff8ec
          name: container-image
